### ISSUE TITLE
Error in installing virt-manager on Monterey

### ISSUE THREAD

**Issue by odoo-mastercore** [Damenly/homebrew-virt-manager#4]
Hi, I encountered the problem in https://github.com/jeffreywildman/homebrew-virt-manager/issues/184 and find your post https://github.com/jeffreywildman/homebrew-virt-manager/issues/184#issuecomment-949225385. I untapped jeffreywildman's repository and uses yours. Then I run brew install virt-manager --HEAD and get this

==> Cloning https://github.com/virt-manager/virt-manager.git
Cloning into '/Users/far/Library/Caches/Homebrew/virt-manager--git'...
==> Checking out branch main
Already on 'main'
Your branch is up to date with 'origin/main'.
==> Installing virt-manager from damenly/virt-manager
==> Patching
==> python3 -m venv --system-site-packages /opt/homebrew/Cellar/virt-manager/HEAD-d12be94_7/libexec
==> python3 -m venv --upgrade-deps /opt/homebrew/Cellar/virt-manager/HEAD-d12be94_7/libexec
==> /opt/homebrew/Cellar/virt-manager/HEAD-d12be94_7/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-insta
==> /opt/homebrew/Cellar/virt-manager/HEAD-d12be94_7/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-insta
==> /opt/homebrew/Cellar/virt-manager/HEAD-d12be94_7/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-insta
==> /opt/homebrew/Cellar/virt-manager/HEAD-d12be94_7/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-insta
==> /opt/homebrew/Cellar/virt-manager/HEAD-d12be94_7/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-insta
==> /opt/homebrew/Cellar/virt-manager/HEAD-d12be94_7/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-insta
==> /opt/homebrew/Cellar/virt-manager/HEAD-d12be94_7/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-insta
==> /opt/homebrew/Cellar/virt-manager/HEAD-d12be94_7/libexec/bin/python setup.py configure --prefix=/opt/homebrew/Cellar/v
Last 15 lines from /Users/far/Library/Logs/Homebrew/virt-manager/10.python:

error: Multiple top-level packages discovered in a flat-layout: ['ui', 'po', 'man', 'data', 'virtinst', 'virtManager'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/damenly/homebrew-virt-manager/issues

Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

**Comment by Damenly** [comment]
Thanks for your report!
However, I'm far away from my daily-use computer.  It's about 7 days left back to my laptop. 
And since it looks like a python bug from https://github.com/jeffreywildman/homebrew-virt-manager/issues/184#issuecomment-1079637318.
Would you try to modify your local file?

**Comment by yadvlz** [comment]
@Damenly hi,
Did you get to the laptop?

**Comment by Damenly** [comment]
@odoo-mastercore @yadvlz  Fixde in master. Please try brew update and reinstall.
 It blames the broken behavior of setup tools and fixed in https://github.com/Damenly/virt-manager/commit/4dbfdd1d983fb5bcbab3ad5711d196a18c11260f

**Comment by yadvlz** [comment]
@Damenly It works. Thanks.

**Comment by odoo-mastercore** [comment]
Hi! @Damenly thanks for your work. I try but error still appears...

My commands...:

$ brew untap Damenly/homebrew-virt-manager 
..
$ brew cleanup -n
..
$ brew tap Damenly/homebrew-virt-manager
..
$ brew install virt-manager --HEAD
..
..
==> Checking out branch main
Already on 'main'
Your branch is up to date with 'origin/main'.
HEAD is now at 4dbfdd1d setuptools: Disable auto discovery
==> Installing virt-manager from damenly/virt-manager
==> Patching
==> python3 -m venv --system-site-packages /opt/homebrew/Cellar/virt-manager/HEAD-4dbfdd1_7/libexec
==> python3 -m venv --upgrade-deps /opt/homebrew/Cellar/virt-manager/HEAD-4dbfdd1_7/libexec
==> /opt/homebrew/Cellar/virt-manager/HEAD-4dbfdd1_7/libexec/bin/pip install -v --no-deps --no-binary :all: --ignor
==> /opt/homebrew/Cellar/virt-manager/HEAD-4dbfdd1_7/libexec/bin/pip install -v --no-deps --no-binary :all: --ignor
==> /opt/homebrew/Cellar/virt-manager/HEAD-4dbfdd1_7/libexec/bin/pip install -v --no-deps --no-binary :all: --ignor
==> /opt/homebrew/Cellar/virt-manager/HEAD-4dbfdd1_7/libexec/bin/pip install -v --no-deps --no-binary :all: --ignor
Last 15 lines from /Users/far/Library/Logs/Homebrew/virt-manager/06.pip:
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/private/tmp/virt-manager--libvirt-python-20220410-345-5u4s2g/libvirt-python-8.1.0/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' install --record /private/tmp/pip-record-2t0ub3ra/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/Cellar/virt-manager/HEAD-4dbfdd1_7/libexec/include/site/python3.9/libvirt-python
  cwd: /private/tmp/virt-manager--libvirt-python-20220410-345-5u4s2g/libvirt-python-8.1.0/
  Running setup.py install for libvirt-python: finished with status 'error'
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> libvirt-python

..
..
$


Thank you!

**Comment by Damenly** [comment]
@odoo-mastercore I reproduced it! It's about libvirt-python and bumping to new 8.2 should fix it.
Would you give it a try?

**Comment by brddd** [comment]
Worked for me on a M1 Monterey mac

**Comment by odoo-mastercore** [comment]
Hi! @Damenly now it's works

Same on M1 Monterey

Thanks!

**Comment by odoo-mastercore** [comment]
Hi @brddd can you run Windows with Qemu on M1 Monterrey?

Thanks
